// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ppqvqwiqwkoduzhjlkdl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBwcXZxd2lxd2tvZHV6aGpsa2RsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzNDkyNTMsImV4cCI6MjA1ODkyNTI1M30.abPBZD4JuRBUSpvEZRQpPhUsFZgAB8QXhVYbONV2pzA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);